
cluster-cancel: "scancel"
restart-times: "0"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "5"
use-conda: "False"
use-singularity: "True"
jobs: "100"
printshellcmds: "True"

# Resource configuration for pipeline jobs, fine-tune if necessary
default-resources:
  - runtime=120
  - mem_mb=12800
  - disk_mb=1000000
set-threads: # map rule names to threads
  - extract_number_of_samples=2
  - find_fixed_homozygote_alt_sites=4
  - remove_fixed_homozygote_alt_sites_merged_vcf=4
  - find_intron_intergenic_variants=2
  - remove_sites_snpEff_vcf=4
  - extract_high_impact_snps=2
  - extract_moderate_impact_snps=2
  - extract_low_impact_snps=2
  - extract_synonymous_variant_snps=2
  - total_load=1
  - realised_load=1
set-resources: # map rule names to resources in general
  - extract_number_of_samples:mem_mb=12800
  - extract_number_of_samples:runtime=30
  - find_fixed_homozygote_alt_sites:mem_mb=25600
  - find_fixed_homozygote_alt_sites:runtime=300
  - remove_fixed_homozygote_alt_sites_merged_vcf:mem_mb=25600
  - remove_fixed_homozygote_alt_sites_merged_vcf:runtime=300
  - find_intron_intergenic_variants:mem_mb=12800
  - find_intron_intergenic_variants:runtime=300
  - remove_sites_snpEff_vcf:mem_mb=25600
  - remove_sites_snpEff_vcf:runtime=300
  - extract_high_impact_snps:mem_mb=12800
  - extract_high_impact_snps:runtime=120
  - extract_moderate_impact_snps:mem_mb=12800
  - extract_moderate_impact_snps:runtime=120
  - extract_low_impact_snps:mem_mb=12800
  - extract_low_impact_snps:runtime=120
  - extract_synonymous_variant_snps:mem_mb=12800
  - extract_synonymous_variant_snps:runtime=120
  - total_load:mem_mb=6400
  - total_load:runtime=30
  - realised_load:mem_mb=6400
  - realised_load:runtime=30